UPPERCASE_LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
LOWERCASE_LETTERS = 'abcdefghijklmnopqrstuvwxyz'
OTHER_LETTERS = 'áéíóúüàãâäèẽêëìĩîïòõôöùũûñÁÉÍÓÚÜÀÃÂÄÈẼÊËÌĨÎÏÒÕÔÖÙŨÛÑ'
NUMBERS = '0123456789'

LETTERS = UPPERCASE_LETTERS + LOWERCASE_LETTERS + OTHER_LETTERS
WHITELIST_TMP = LOWERCASE_LETTERS + NUMBERS
WHITELIST_CONTENT = LETTERS + NUMBERS

ID_STRING_LENGTH = 12

PYTHON_CMD = '/usr/bin/python3'
RENDER_CMD = '/home/gustavo/Work/gitrepos/GH/definitive/definitive.py'
RENDER_OPT_WORD_CLASS = '-c noun'

ERROR_WORD = 'error'
ERROR_WORD_CLASS = 'bummer'
ERROR_DEFINITION = 'action often performed by naught kids messing up with the inputs'
ERROR_SEE_ALSO = 'oops'
ERROR_AVATAR = 'troll'

WORD_MAX_LENGTH = 20
DEFINITION_MAX_LENGTH = 160
SEE_ALSO_MAX_LENGTH = 20

IMG_TEXT_COLOR = "#042c49"
IMG_BORDER_COLOR = IMG_TEXT_COLOR
IMG_TOP_MARGIN = "35"

BASE_DELAY = 0.2
MAX_DELAY_DELTA = 0.2
